### ISSUE TITLE
System.AccessViolationException in yr_compiler_create

### ISSUE THREAD

**Issue by admiralbenbou** [microsoft/libyara.NET#10]
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at yr_compiler_create(_YR_COMPILER** )
   at libyaraNET.Compiler..ctor()
   at libyaraNET.Compiler.CompileRulesFile(String path)
   at libyaraNET.QuickScan.Memory(IntPtr buffer, Int32 length, String rulesPath, ScanFlags flags)
   at libyaraNET.QuickScan.Memory(Byte[] buffer, String rulesPath, ScanFlags flags)

LibyaraNet version 4.0.2

**Comment by swannman** [comment]
@admiralbenbou could you please share sample code and a Yara rule that demonstrates this issue? Thanks!

**Comment by admiralbenbou** [comment]
Hello. Sure, [office.txt](https://github.com/microsoft/libyara.NET/files/4759893/office.txt)
`
var stopwatch = new Stopwatch();
stopwatch.Start();
try{
        List<ScanResult> scanResults = QuickScan.Memory(buffer, rulesPath, ScanFlags.Fast );
        stopwatch.Stop();                
        if (scanResults.Any())              
                return true;
        return false;
}
`

**Comment by admiralbenbou** [comment]
may be important. this method is used in a multi-threaded application - a transport agent for exchange. and an exception does not occur immediately - only after processing several emails (several method calls)

**Comment by shaheeraliwrg** [comment]
@swannman I'm experiencing the same issue, is there any update?

**Comment by admiralbenbou** [comment]
> 
> 
> @swannman I'm experiencing the same issue, is there any update?

i asked my colleagues - c developers to make for me fixed version and i use it now https://github.com/k-sec-tools/ExchangeFilter/tree/main/libyaranet. but our version is few commits behind the official repo

**Comment by shaheeraliwrg** [comment]
@admiralbenbou That's fantastic! Could you tell me which version of Yara was used? Current version is 4.1.3 please check this [link](https://github.com/VirusTotal/yara) for reference.

**Comment by admiralbenbou** [comment]
@shaheeraliwrg not sure, it was 3.8.0 or 3.8.1. Be careful cause in yarav4.* API has been changed

**Comment by shaheeraliwrg** [comment]
Thanks for sharing this, it's really helpful @admiralbenbou

**Comment by swannman** [comment]
@admiralbenbou would you be open to creating a pull request so we can merge your changes into this repro?

**Comment by admiralbenbou** [comment]
@swannman dont think it will make sense. my colleagues just fixed libyara v3.7.x code(bcause the main bug was in this librara) and rebuilt libyaraNET with it. and because libyara v3 is not actual version, i dont think we have to pull this changes to main libyara repo

**Comment by shaheeraliwrg** [comment]
@swannman How can we upgrade libyara.net's YARA version? Does there exist any documentation or guideline to do this? I would like to upgrade the YARA version to the latest, as it may solve the issues listed above. Can you please help me upgrade the version?

**Comment by swannman** [comment]
@shaheeraliwrg libyara.NET ships with YARA 4.0.2 today. We consume YARA from [this nuget](https://www.nuget.org/packages/Microsoft.O365.Security.Native.Libyara/) which we build from the vcpkg project [here](https://github.com/microsoft/vcpkg/tree/master/ports/yara).

It looks like the latest version of YARA in vcpkg is 4.1.1. Is there a fix between 4.0.2 and 4.1.1 for the issue that you were seeing?

**Comment by shaheeraliwrg** [comment]
@swannman I'm not sure if this issue has been fixed in the latest Yara version. But if possible we should go with the latest version (there are tons of fixes in the latest version). I tried upgrading the libyara.Net with the latest yara version, but I wasn't able to finish due to the lack of documentation.

**Comment by gnh1201** [comment]
The version is libyara.NET 4.5.1, targeting x86, and the runtime is .NET Framework 4.8.

```
System.AccessViolationException
    at yr_rules_scan_fd(YR_RULES* , Void* , Int32 , IntPtr , Void* , Int32 )
    at libyaraNET.Scanner.ScanFile(String path, Rules rules, ScanFlags flags)
    at (My Application)
```

I used the official example rule: https://yara.readthedocs.io/en/stable/writingrules.html

```
rule ExampleRule
{
    strings:
        $my_text_string = "text here"
        $my_hex_string = { E2 34 A1 C8 23 FB }

    condition:
        $my_text_string or $my_hex_string
}
```
